import {createHash} from 'node:crypto'

import {readFile, writeFile} from 'fs-extra'

const output = new URL('../src/lib/procfs/collectorSource.ts', import.meta.url)
const build = await Bun.build({
  entrypoints: [new URL('../src/lib/procfs/collector/main.ts', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')],
  target: 'bun',
  minify: true,
  sourcemap: 'none',
})
if (!build.success) {
  throw new AggregateError(build.logs, 'Failed to bundle the Bun collector.')
}
const source = await build.outputs[0].text()
const revision = createHash('sha256').update(source).digest('hex')
const generated = '// Generated by scripts/embedCollector.ts; edit collector/*.ts instead.\n'
  + `export const collectorRevision = ${JSON.stringify(revision)}\n`
  + `export const collectorSource = ${JSON.stringify(source)}\n`
if (Bun.argv.includes('--check')) {
  const current = await readFile(output, 'utf8').catch(() => '')
  if (current !== generated) { throw new Error('The embedded collector is stale. Run bun run generate.') }
} else {
  await writeFile(output, generated)
}
