import {createHash} from 'node:crypto'

import {readFile, writeFile} from 'fs-extra'

const input = new URL('../src/lib/procfs/collector.py', import.meta.url)
const output = new URL('../src/lib/procfs/collectorSource.ts', import.meta.url)
const source = (await readFile(input, 'utf8')).replaceAll('\r\n', '\n')
const revision = createHash('sha256').update(source).digest('hex')
const generated = '// Generated by scripts/embedCollector.ts; edit collector.py instead.\n'
  + `export const collectorRevision = ${JSON.stringify(revision)}\n`
  + `export const collectorSource = ${JSON.stringify(source)}\n`
if (Bun.argv.includes('--check')) {
  const current = await readFile(output, 'utf8').catch(() => '')
  if (current !== generated) {
    throw new Error('The embedded collector is stale. Run bun run generate.')
  }
} else {
  await writeFile(output, generated)
}
